replicaCount: 1

image:
  name: service-hello-api
  repository: gcr.io/dataflow-chiper/hello-server/main:183c662
  pullPolicy: IfNotPresent
  tag: "1"
  
service:
  type: ClusterIP
  port: 80
  targetport: 3000
  name: service-hello-api


configMap:
  data:
    NAME: MICHAEL
